export  interface ILockListData {
    "lockInwardId": string,
    "inwardDate": string,
    "lockId": string,
    "lockNumber": string,
    "lockIMEIId": string,
    "lockIMEINumber": string,
    "statusEnumId": string,
    "statusName": string,
    "remarks": string,
    "actionRemarks": string,
    "createdOnDate": string,
    "createdByLoginUserId": string,
    "createdByUserName": string,
    "createdByUserTypeEnumId":string,
    "createdByUserTypeName": string,
    "updatedLoginUserId": string,
    "updatedLoginUserName": string,
    "updatedOnDate": string,
    "updatedByUserTypeEnumId": string,
    "updatedByUserTypeName": string,
}