export interface IaddUpdateZone {  
        id:number,
        name: string,
        latitude: string,
        longitude:string,
        zoneSize: number,
        zoneCapacity: number,
        zoneAddress: string,
        stateId: number,
        stateName: string,
        cityId:number,
        cityName: string,
        statusEnumId:number,
        statusName: string,
        remarks: string,
        actionRemarks: string,
        createdOnDate: string,
        createdByLoginUserId: number,
        createdByUserName: string,
        createdByUserTypeEnumId:number,
        createdByUserTypeName: string,
        updatedLoginUserId:number,
        updatedLoginUserName: string,
        updatedOnDate: string,
        updatedByUserTypeEnumId: number,
        updatedByUserTypeName: string,
        areaId:number
    
  }